### ISSUE TITLE
iPhone rear camera

### ISSUE THREAD

**Issue by domdewom** [ktcy/CameraLayer#10]
So far I cannot find a way to activate the rear camera of the iPhone (iPhone X) on iOS 11.4. I tried 

# Option 1
camera = new CameraLayer(facing: "back")

# Option 2
camera = new CameraLayer()
camera.facing = "back"

Both are not working. I only get the front facing one to work...

Is there another way to do it?

**Comment by ktcy** [comment]
I found the facing option seems not to working on recent web browsers. Could you try this modified version of CameraLayer.coffee?
https://raw.githubusercontent.com/ktcy/CameraLayer/facing-fix/src/CameraLayer.coffee

**Comment by domdewom** [comment]
Just tried it out. It seems to work. Yeah! Awesome, thank you. What did you change? Looks like the start method with the enumerateDevices() changed...

**Comment by ktcy** [comment]
Thank you for trying. My code was a bit dated and not matching with today's spec of web standards, so I fixed a lot of it.
https://github.com/ktcy/CameraLayer/commit/6b664804a8b3327dd0c1bcf616fe1d06f14eddc0

I'm going to merge it to the master branch after polishing it up.

**Comment by domdewom** [comment]
Hey got another question, whats the best way to get the ImageData of the videostream? Something along these lines wouldnt work: 
```
getImageD: (width = @width, height = @height, ratio = window.devicePixelRatio) ->
    canvas = document.createElement("canvas")
    canvas.width = ratio * width
    canvas.height = ratio * height

    context = canvas.getContext("2d")

    context.drawImage(@player, 0, 0, width, height)
    imaged = context.getImageData(0, 0, width, height)

    imaged
```
Also is it possible the capture part doesnt work anymore now?

**Comment by ktcy** [comment]
CameraLayer's capture method draws the video stream to a canvas, then calls callback with a URL of the canvas's image data. You can set this URL to a layer's image property to show the captured image.
https://github.com/ktcy/CameraLayer#capture

If you want to get the image data itself, it can be done like this:
```coffee
camera = new CameraLayer()
camera.start()

getImageData = ->
  videoElement = camera.player
  width = videoElement.videoWidth
  height = videoElement.videoHeight

  canvas = document.createElement("canvas")
  canvas.width = width
  canvas.height = height

  context = canvas.getContext("2d")
  context.drawImage(videoElement, 0, 0)
  imageData = context.getImageData(0, 0, width, height)

  imageData
```
