### ISSUE TITLE
Example of flipping the camera?

### ISSUE THREAD

**Issue by chriswangux** [ktcy/CameraLayer#11]
Thanks for the module! This is the only way I can get Framer to work with a camera. 

Could you add an example of how to flip the front/back facing camera?

I tried 
`camera.facing = "front"`
and
`camera.toggleFacing()`

but neither seem to work. (getting a blank screen after setting the facing or calling the toggleFacing method).

**Comment by ktcy** [comment]
Could you try this version of the module?
https://raw.githubusercontent.com/ktcy/CameraLayer/facing-fix/src/CameraLayer.coffee

I had asked a similar question before (https://github.com/ktcy/CameraLayer/issues/10), so I had made a quick fix in that time, and just remembered that I forgot to push it to the master branch.

**Comment by chriswangux** [comment]
Awesome. that worked! 

Thank you so much!
