### ISSUE TITLE
MediaStreamTrack.getSources() is deprecated

### ISSUE THREAD

**Issue by spicyhappy** [ktcy/CameraLayer#5]
Code no longer works for Chrome 56
See https://developers.google.com/web/updates/2016/12/chrome-56-deprecations and https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

**Comment by ktcy** [comment]
Thanks. I fixed it. 08d3cc1

**Comment by spicyhappy** [comment]
Awesome! Just tested it on my end and it works perfectly.
