### ISSUE TITLE
Record video with layer?

### ISSUE THREAD

**Issue by blaineb** [ktcy/CameraLayer#7]
@ktcy this module is awesome.  Do you think it would be easily extended to allow for capturing / replaying video?

**Comment by ktcy** [comment]
Google Chrome and Firefox have API related to video recording, so I think we can use it to record video via CameraLayer. I started looking into this now:
https://developers.google.com/web/updates/2016/01/mediarecorder

**Comment by blaineb** [comment]
My JS skills are really limited, but I'm hoping to figure this out in the following week.  I essentially got it working (although not as module).  I can't figure out how to get the captured video to have the same dimensions as the CameraLayer's dimensions, or why its not getting sound.  

https://framer.cloud/rxWgp/

**Comment by ktcy** [comment]
I added some methods and events to CameraLayer to support video recording. This is a work in progress and not yet pushed to the repository.

https://framer.cloud/pSnLC/

CameraLayer starts video recording by calling `startRecording()`, and stops by `stopRecording()`.

After when the video recording was stopped, CameraLayer emits `record` event with a URL of the video. `onRecord()` is a convenient way to receive this event.

```coffee
viewer = new VideoLayer()

camera = new CameraLayer()
camera.onRecord (url) -> viewer.video = url
camera.start()

button = new Layer()
button.onTouchStart -> camera.startRecording()
button.onTouchEnd -> camera.stopRecording()
```

And you may have already solved by yourself, but I have some comments on your questions:
- The current version of CameraLayer doesn't use the audio stream from camera device. This is why you didn't get the sound. I modified it to use the audio in the work in progress version.
- Camera device is streaming a fixed size of image regardless of the layer's dimensions, so you have to resize the image to match dimensions to the layer. The simplest way is to set VideoLayer's `player.style.objectFit` property to `'cover'`.

**Comment by blaineb** [comment]
Rock on!!  This is super awesome.  Exactly what I was envisioning!  Thanks so much for wrapping it up into your module.  It's killer.

**Comment by ktcy** [comment]
This has been pushed to the repository and documented in README.
