### ISSUE TITLE
How do we manipulate the recorded video?

### ISSUE THREAD

**Issue by nitins1** [ktcy/CameraLayer#8]
What can we do with the video URL? How would we play the recorded video? Is it linked to a VideoLayer?

**Comment by ktcy** [comment]
To play the recorded video, you need to create VideoLayer and set the video URL to it.

```coffee
# Create VideoLayer
videoLayer = new VideoLayer()

# Set autoplay
# (or manually call videoLayer.player.play() after setting videoURL)
videoLayer.player.autoplay = true

# Set videoURL to VideoLayer's video property
cameraLayer.onRecord (videoURL) ->
  videoLayer.video = videoURL
```

**Comment by nitins1** [comment]
@ktcy Thanks, I accidentally looked over that line of code in the docs!
